version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: banco_pix_pg
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: banco_pix
    ports:
      - '5432:5432'
    volumes:
      - banco_pix_data:/var/lib/postgresql/data

volumes:
  banco_pix_data:
